"""describe_schema_change

Revision ID: 39e652e87810
Revises: dac54733a09a
Create Date: 2026-10-08 10:24:24.333120
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '39e652e87810'
down_revision: str | None = 'dac54733a09a'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
